### ISSUE TITLE
Formula from 01-1_Linear Algebra with NumPy.ipynb different from conventional

### ISSUE THREAD

**Issue by codenamewei** [CertifaiAI/machine-learning-fundamentals#19]
Function of **add_row** different from source in terms of parameter sequence of _i_ and _j_

From Website: https://secure.math.ubc.ca/~pwalls/math-python/linear-algebra/solving-linear-systems/
<img width="932" alt="Screenshot_2021-06-07_at_8 50 03_PM" src="https://user-images.githubusercontent.com/33477318/121142094-379e2180-c86e-11eb-9ec2-52acee8f401c.png">

From Notebook:

<img width="534" alt="Screenshot_2021-06-07_at_8 50 32_PM" src="https://user-images.githubusercontent.com/33477318/121142080-34a33100-c86e-11eb-811a-b2cbdee7ffe6.png">

Suggest fix to follow the formula from the website as conventionally horizontal axis (i / x) comes before vertical axis( j, y)

**Comment by annabelle-97** [comment]
Fixed
